version: '3'

services:
  php:
    container_name: test-php
    build: ./docker
    volumes:
    - .:/var/www

  nginx:
    image: nginx
    container_name: test-nginx
    ports:
    - 20080:80
    volumes:
    - .:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 13306:3306
